In [2]:
import tensorflow as tf
import numpy as np

In [3]:
a = tf.constant(15)
b = tf.constant(20)
print(a+b)
print(a-b)
print(a*b)

tf.Tensor(35, shape=(), dtype=int32)
tf.Tensor(-5, shape=(), dtype=int32)
tf.Tensor(300, shape=(), dtype=int32)


In [2]:
# input
x = np.random.rand(100).astype(np.float32)
print(x)

[0.73387176 0.97820073 0.21187808 0.0358735  0.07826528 0.91215533
 0.33276623 0.66061956 0.26210904 0.4238264  0.80457777 0.16611959
 0.09604524 0.7539399  0.4896322  0.5820778  0.916564   0.33874416
 0.32435584 0.29127806 0.27041376 0.34385    0.08972409 0.6532004
 0.37358424 0.9208215  0.3326017  0.7488958  0.28268692 0.03111845
 0.05601687 0.3313162  0.23734419 0.26888192 0.21177411 0.8107789
 0.7380227  0.09336556 0.35597512 0.2624742  0.92519015 0.2778356
 0.6298493  0.6388223  0.30019492 0.3616691  0.19074301 0.6309947
 0.8463066  0.67510957 0.7604725  0.9748005  0.31967908 0.7218257
 0.0183755  0.6920954  0.22277404 0.8303785  0.15089674 0.62719893
 0.939995   0.96751136 0.41275337 0.35171285 0.21520819 0.80309427
 0.67646044 0.594621   0.40903625 0.763276   0.7609124  0.65924746
 0.50847274 0.04408352 0.92960644 0.5614242  0.53823453 0.52517056
 0.91213626 0.00126517 0.09925459 0.44783852 0.09583116 0.6327463
 0.60889816 0.8227311  0.04133055 0.49857563 0.9047547  0.5700745
 0

In [5]:
# output - observed
y = x * 0.2 + 0.2
# Weight
W = tf.Variable(tf.random.normal([1]))
# bias
b = tf.Variable(tf.zeros([1]))

In [6]:
# Create a function for MSE - mean squared error
def mse_loss():
  ypred = W * x + b
  loss = tf.reduce_mean(tf.square(ypred-y))
  return loss

In [7]:
# Optimizer
optimizer = tf.keras.optimizers.Adam()

In [8]:
# Iterations
for step in range(5000):
  optimizer.minimize(mse_loss,var_list=[W,b])
  if step % 500 == 0:
    print(step, W.numpy(), b.numpy())

0 [-0.3673859] [0.001]
500 [-0.05266239] [0.29018274]
1000 [0.02834991] [0.29162404]
1500 [0.08650305] [0.26087362]
2000 [0.1357939] [0.23443127]
2500 [0.17005995] [0.21605453]
3000 [0.18905447] [0.2058691]
3500 [0.19706775] [0.20157228]
4000 [0.19947399] [0.20028207]
4500 [0.19994399] [0.20003003]


# KERAS

In [9]:
# Step 1 - Load the dataset
from numpy import loadtxt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [23]:
import numpy
dataset = numpy.loadtxt('Documents/pima-indians-diabetes.csv',delimiter=',',skiprows=1)
dataset

array([[1.00e+00, 8.50e+01, 6.60e+01, ..., 3.51e-01, 3.10e+01, 0.00e+00],
       [8.00e+00, 1.83e+02, 6.40e+01, ..., 6.72e-01, 3.20e+01, 1.00e+00],
       [1.00e+00, 8.90e+01, 6.60e+01, ..., 1.67e-01, 2.10e+01, 0.00e+00],
       ...,
       [5.00e+00, 1.21e+02, 7.20e+01, ..., 2.45e-01, 3.00e+01, 0.00e+00],
       [1.00e+00, 1.26e+02, 6.00e+01, ..., 3.49e-01, 4.70e+01, 1.00e+00],
       [1.00e+00, 9.30e+01, 7.00e+01, ..., 3.15e-01, 2.30e+01, 0.00e+00]])

In [24]:
x = dataset[:,0:8]
print(type(x))
print(x.shape)
y = dataset[:,8]
print(y)

<class 'numpy.ndarray'>
(767, 8)
[0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1.
 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1.
 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1.
 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0.
 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0. 1.
 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0.
 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 1.
 1. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 1. 1. 1.
 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0. 0.
 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1.
 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1. 0.
 0. 0. 1. 1. 1. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1.
 0. 1. 0. 0. 1. 0.

In [30]:
model = Sequential()


The model expects row of data with 8 variables 12 = nodes

In [31]:
model.add(Dense(12, input_shape=(8,), activation='relu'))

Hidden Layer 8 = nodes

In [32]:
model.add(Dense(8, activation='relu'))

In [33]:
# Output layer
model.add(Dense(1,activation='sigmoid'))

Step 3 - Compile the Keras model loss (error) optimizer (adam) metrics = accuracy

In [35]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

Step 4 - Fit / Train the model 1 = Epochs - number of iterations / passes 2 - Batch - sample data

In [36]:
model.fit(x,y, epochs=50, batch_size=10)

Epoch 1/50
77/77 [==============================] - 2s 6ms/step - loss: 2.2219 - accuracy: 0.6323
Epoch 2/50
77/77 [==============================] - 0s 5ms/step - loss: 0.9864 - accuracy: 0.5984
Epoch 3/50
77/77 [==============================] - 0s 5ms/step - loss: 0.8426 - accuracy: 0.6389
Epoch 4/50
77/77 [==============================] - 0s 4ms/step - loss: 0.7646 - accuracy: 0.6428
Epoch 5/50
77/77 [==============================] - 0s 5ms/step - loss: 0.7380 - accuracy: 0.6532
Epoch 6/50
77/77 [==============================] - 1s 7ms/step - loss: 0.7212 - accuracy: 0.6532
Epoch 7/50
77/77 [==============================] - 1s 8ms/step - loss: 0.6766 - accuracy: 0.6714
Epoch 8/50
77/77 [==============================] - 1s 7ms/step - loss: 0.6596 - accuracy: 0.6871
Epoch 9/50
77/77 [==============================] - 0s 4ms/step - loss: 0.6535 - accuracy: 0.6845
Epoch 10/50
77/77 [==============================] - 0s 5ms/step - loss: 0.6416 - accuracy: 0.7001
Epoch 11/50
77/77 [

In [37]:
model.evaluate(x,y)

24/24 [==============================] - 1s 4ms/step - loss: 0.5192 - accuracy: 0.7588


[0.5191866159439087, 0.7588005065917969]

# Theano

In [4]:
import theano
from theano import *
import theano.tensor as T
import numpy as np
import pandas as pd
from theano import function

WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.


In [7]:
# scalar variables
v1 = T.dscalar('v1')
v2 = T.scalar('v2')
# subtraction
sres = v1-v2

f=function([v1,v2],sres)
f(7,5)

array(2.)

In [8]:
sres

Elemwise{sub,no_inplace}.0

In [68]:
#add
ares = v1+v2
#convert the results into functions
calcsres = theano.function([v1,v2],sres)
calcares = theano.function([v1,v2],ares)
calcares(12,23)
calcsres(13,12)
x = T.dmatrix('x')
y = T.dmatrix('y')

In [69]:
z = x+y
func = function([x,y],z)
m1 = [
[1,2],
[3,4]
]
m2 = [
[4,5],
[6,7]
]
func(m1,m2)

array([[ 5.,  7.],
       [ 9., 11.]])

In [9]:
# Declaring variable
a = tensor.dmatrix('a')
 
# Sigmoid function
sig = 1 / (1 + tensor.exp(-a))
 
# Now it takes matrix as parameters
log = theano.function([a], sig)
 
# Calling function
print(log([[0, 1], [-1, -2]]))

[[0.5        0.73105858]
 [0.26894142 0.11920292]]


# Pytorch

In [71]:
import torch
import numpy as np

# Using Data

In [72]:
data = [
[1,2],
[3,4]
]
x_data = torch.tensor(data)

In [73]:
print(type(x_data))

<class 'torch.Tensor'>


# Using numpy array

In [74]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)
print(type(x_np))

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
<class 'torch.Tensor'>


# Using another sensor

In [75]:
x_ones = torch.ones_like(x_data)
print("One Tensor: \n",x_ones)
x_rand = torch.rand_like(x_data,dtype=torch.float)
print(x_rand)

One Tensor: 
 tensor([[1, 1],
        [1, 1]])
tensor([[0.4499, 0.7531],
        [0.8280, 0.6249]])


more ways to create sensor

In [76]:
shape = (2,3)
random_tensor = torch.rand(shape)
print(random_tensor)
print(type(random_tensor))
ones_tensor = torch.ones(shape)
print(ones_tensor)
print(type(ones_tensor))
zeros_tensor = torch.zeros(shape)
print(zeros_tensor)
print(type(zeros_tensor))
tensor = torch.rand(3,4)
print(tensor)
tensor.shape
tensor.dtype
tensor.device

tensor([[0.2515, 0.6502, 0.8014],
        [0.0092, 0.9831, 0.5400]])
<class 'torch.Tensor'>
tensor([[1., 1., 1.],
        [1., 1., 1.]])
<class 'torch.Tensor'>
tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>
tensor([[0.2457, 0.5619, 0.0221, 0.8140],
        [0.3632, 0.9244, 0.5942, 0.2731],
        [0.9855, 0.0196, 0.6192, 0.7281]])


device(type='cpu')

# Tensor Operation

In [77]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print("Device tensor is stored in ", tensor.device)

# Indexing ,Slicing

In [78]:
tensor = torch.ones(4,4)
print(tensor)
print(tensor)
tensor1 = torch.zeros(4,4)
print(tensor1)
tensor2 = torch.cat([tensor,tensor1])
print(tensor2)
# Multiply Operation
tensor.mul(tensor1)
tensor * tensor1
tensor.T
# inplace - change the original tensor
tensor.add_(3)
print(tensor)
# from tensor to numpy
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)
print(type(n))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])
tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
